apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - backend-deployment.yaml
  - backend-service.yaml
  - frontend-deployment.yaml
  - frontend-service.yaml
  - postgres-statefulset.yaml
  - postgres-service.yaml
  - backend-hpa.yaml
  - frontend-hpa.yaml
  - ingress.yaml
