apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: backend-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore
  target:
    name: backend-secret
    creationPolicy: Owner
  data:
    - secretKey: DB_PASSWORD
      remoteRef:
        key: healthcare/stage/backend
        property: DB_PASSWORD
    - secretKey: SECRET_KEY
      remoteRef:
        key: healthcare/stage/backend
        property: SECRET_KEY
